---
batch_size: 2
learning_rate: 0.005
epochs: 500
seq_len: 200

dropout: 0.5
momentum: 0.0005
weight_decay: 0.00005
scheduling: True
warm_up: 2


input_shape: 2048
token_embedding: 1024
hidden_layer: 2048
projection_size: 512
output_shape: 128
gpu: 1

pooling: "none"

experts: ["test-video-embeddings", "test-location-embeddings", "test-img-embeddings", "audio-embeddings"]
train_experts: ["img-embeddings"]
test_experts: ["test-img-embeddings"]
n_labels: 15
n_heads: 4
frame_agg: "none"
frame_id: 0

mixing_method: "none"
cat_norm: False
cat_softmax: False

architecture: "post-trans"

device: 1
aggregation: "none"

save_path: "/trained_models/mmx/transformer/"
